// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYd4I-K471eZz75OtJ60-DoBfTqd7_3IQ',
    appId: '1:241212286533:web:8d4a44097f874c4b36252c',
    messagingSenderId: '241212286533',
    projectId: 'taqwa-1d7bf',
    authDomain: 'taqwa-1d7bf.firebaseapp.com',
    storageBucket: 'taqwa-1d7bf.firebasestorage.app',
    measurementId: 'G-F3D3QL1Q09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkr4I5Y5FxeZ58wyDbO6rq4BXQY2IfP0Q',
    appId: '1:241212286533:android:972840c4543b024e36252c',
    messagingSenderId: '241212286533',
    projectId: 'taqwa-1d7bf',
    storageBucket: 'taqwa-1d7bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN28LpaXGDzlq1IPoL34nXvPfu-R206rM',
    appId: '1:241212286533:ios:a37c20d63cc48efb36252c',
    messagingSenderId: '241212286533',
    projectId: 'taqwa-1d7bf',
    storageBucket: 'taqwa-1d7bf.firebasestorage.app',
    iosBundleId: 'com.example.taqwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN28LpaXGDzlq1IPoL34nXvPfu-R206rM',
    appId: '1:241212286533:ios:a37c20d63cc48efb36252c',
    messagingSenderId: '241212286533',
    projectId: 'taqwa-1d7bf',
    storageBucket: 'taqwa-1d7bf.firebasestorage.app',
    iosBundleId: 'com.example.taqwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYd4I-K471eZz75OtJ60-DoBfTqd7_3IQ',
    appId: '1:241212286533:web:fc5c0e6dadd0bb4136252c',
    messagingSenderId: '241212286533',
    projectId: 'taqwa-1d7bf',
    authDomain: 'taqwa-1d7bf.firebaseapp.com',
    storageBucket: 'taqwa-1d7bf.firebasestorage.app',
    measurementId: 'G-WHSRPSJTKS',
  );
}
